YuGiOhCards/Controllers/FotoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YuGiOhCards.Data;
using YuGiOhCards.Models;

namespace YuGiOhCards.Controllers
{
    public class FotoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnviroment;

        public FotoController(ApplicationDbContext context, IWebHostEnvironment hostingEnviroment)
        {
            _context = context;
            _hostingEnviroment = hostingEnviroment;
        }

        // GET: Foto
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Foto.Include(f => f.Urun);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Foto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foto = await _context.Foto
                .Include(f => f.Urun)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foto == null)
            {
                return NotFound();
            }

            return View(foto);
        }

        // GET: Foto/Create
        public IActionResult Create()
        {
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Ad");
            return View();
        }

        // POST: Foto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ResimAd,UrunId")] Foto foto)
        {
            if (ModelState.IsValid)
            {
                //WebHostEnvironment

                string webRootPath = _hostingEnviroment.WebRootPath;
                var files = HttpContext.Request.Form.Files;


                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(webRootPath, @"Images/UrunFoto");
                var extension = Path.GetExtension(files[0].FileName);//yüklenen resim dosyasının uzantısı

                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                foto.ResimAd = @"/Images/UrunFoto" + "/" + fileName + extension;

                //***************
                _context.Add(foto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Ad", foto.UrunId);
            return View(foto);
        }

        // GET: Foto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foto = await _context.Foto.FindAsync(id);
            if (foto == null)
            {
                return NotFound();
            }
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Ad", foto.UrunId);
            return View(foto);
        }

        // POST: Foto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ResimAd,UrunId")] Foto foto)
        {
            if (id != foto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(foto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FotoExists(foto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Ad", foto.UrunId);
            return View(foto);
        }

        // GET: Foto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foto = await _context.Foto
                .Include(f => f.Urun)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foto == null)
            {
                return NotFound();
            }

            return View(foto);
        }

        // POST: Foto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foto = await _context.Foto.FindAsync(id);
            _context.Foto.Remove(foto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FotoExists(int id)
        {
            return _context.Foto.Any(e => e.Id == id);
        }
    }
}

YuGiOhCards/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YuGiOhCards.Data;
using YuGiOhCards.Models;

namespace YuGiOhCards.Controllers
{
    public class SepetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SepetController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sepet
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Sepet.Include(s => s.ApplicationUser).Include(s => s.Urun);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Sepet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sepet = await _context.Sepet
                .Include(s => s.ApplicationUser)
                .Include(s => s.Urun)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sepet == null)
            {
                return NotFound();
            }

            return View(sepet);
        }

        // GET: Sepet/Create
        public IActionResult Create()
        {
            ViewData["MusteriId"] = new SelectList(_context.ApplicationUser, "Id", "Id");
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Id");
            return View();
        }

        // POST: Sepet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UrunId,MusteriId,Miktar,Fiyat,SiparisOk")] Sepet sepet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sepet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MusteriId"] = new SelectList(_context.ApplicationUser, "Id", "Id", sepet.MusteriId);
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Id", sepet.UrunId);
            return View(sepet);
        }

        // GET: Sepet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sepet = await _context.Sepet.FindAsync(id);
            if (sepet == null)
            {
                return NotFound();
            }
            ViewData["MusteriId"] = new SelectList(_context.ApplicationUser, "Id", "Id", sepet.MusteriId);
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Id", sepet.UrunId);
            return View(sepet);
        }

        // POST: Sepet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UrunId,MusteriId,Miktar,Fiyat,SiparisOk")] Sepet sepet)
        {
            if (id != sepet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sepet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SepetExists(sepet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MusteriId"] = new SelectList(_context.ApplicationUser, "Id", "Id", sepet.MusteriId);
            ViewData["UrunId"] = new SelectList(_context.Urun, "Id", "Id", sepet.UrunId);
            return View(sepet);
        }

        // GET: Sepet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sepet = await _context.Sepet
                .Include(s => s.ApplicationUser)
                .Include(s => s.Urun)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sepet == null)
            {
                return NotFound();
            }

            return View(sepet);
        }

        // POST: Sepet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sepet = await _context.Sepet.FindAsync(id);
            _context.Sepet.Remove(sepet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SepetExists(int id)
        {
            return _context.Sepet.Any(e => e.Id == id);
        }
        public class sepeteekle
        {
            public int UrunId { get; set; }

            public int Adet { get; set; }
            public string UrunAd { get; set; }
            public double UrunFiyat { get; set; }
            public string UrunFoto { get; set; }
            public string UrunKategori { get; set; }

            public int KategoriId { get; set; }


        }
    }
}

YuGiOhCards/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YuGiOhCards.Data;
using YuGiOhCards.Models;

namespace YuGiOhCards.Controllers
{
    public class UrunController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UrunController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Urun
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Urun.Include(u => u.Kategori);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Urun/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urun = await _context.Urun
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // GET: Urun/Create
        public IActionResult Create()
        {
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Ad");
            return View();
        }

        // POST: Urun/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ad,Fiyat,Miktar,Aciklama,Birim,UretimYeri,KategoriId")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                _context.Add(urun);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Ad", urun.KategoriId);
            return View(urun);
        }

        // GET: Urun/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urun = await _context.Urun.FindAsync(id);
            if (urun == null)
            {
                return NotFound();
            }
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Ad", urun.KategoriId);
            return View(urun);
        }

        // POST: Urun/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ad,Fiyat,Miktar,Aciklama,Birim,UretimYeri,KategoriId")] Urun urun)
        {
            if (id != urun.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(urun);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UrunExists(urun.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Ad", urun.KategoriId);
            return View(urun);
        }

        // GET: Urun/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urun = await _context.Urun
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // POST: Urun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var urun = await _context.Urun.FindAsync(id);
            _context.Urun.Remove(urun);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UrunExists(int id)
        {
            return _context.Urun.Any(e => e.Id == id);
        }
    }
}

YuGiOhCards/Views/Shared/_Layout.cshtml
@inject LanguageService language

@{
    Layout = null;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - YuGiOhCards</title>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Modern Business - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/template/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/template/css/styles.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="d-flex flex-column h-100">

    <main class="flex-shrink-0">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">@language.Getkey("Yu Gi Oh Kartları")</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">@language.Getkey("Ana_Sayfa")</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">@language.Getkey("İletişim")</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="UrunlerSayfası" asp-action="Listele">@language.Getkey("Ürünler")</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@language.Getkey("Kategoriler")</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                <li><a class="dropdown-item" asp-controller="ToptanUrunler" asp-action="toptanlistele">@language.Getkey("Toptan Ürünler")</a></li>
                                <li><a class="dropdown-item" asp-controller="PerakendeUrunler" asp-action="perakendelistele">@language.Getkey("Perakende Ürünler")</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@language.Getkey("Yönetici")</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                <li><a class="dropdown-item" asp-controller="Foto" asp-action="Index">@language.Getkey("Fotoğraflar")</a></li>
                                <li><a class="dropdown-item" asp-controller="IndirimliUrunler" asp-action="Index">@language.Getkey("İndirimli Ürünler")</a></li>
                                <li><a class="dropdown-item" asp-controller="Kampanya" asp-action="Index">@language.Getkey("Kampanyalar")</a></li>
                                <li><a class="dropdown-item" asp-controller="Kategori" asp-action="Index">@language.Getkey("Kategoriler")</a></li>
                                <li><a class="dropdown-item" asp-controller="Sepet" asp-action="Index">@language.Getkey("Sepet")</a></li>
                                <li><a class="dropdown-item" asp-controller="Siparis" asp-action="Index">@language.Getkey("Sipariş")</a></li>
                                <li><a class="dropdown-item" asp-controller="SiparisDetay" asp-action="Index">@language.Getkey("Sipariş Detay")</a></li>
                                <li><a class="dropdown-item" asp-controller="Urun" asp-action="Index">@language.Getkey("Ürünler")</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <form class="d-flex">
                        <button class="btn btn-outline-light" asp-controller="Sepet" asp-action="Index">
                            <i class="bi-cart-fill me-1"></i>
                            @language.Getkey("Sepetim")

                        </button>
                    </form>

                    @*<ul class="dropdown-menu bg-primary">

                            <li class="nav-item">
                                <a -asp-area="" asp-controller="Home" asp-action="Index">@language.Getkey("Ana_Sayfa")</a>
                            </li>
                            <li class="nav-item">
                                <a -asp-area="" asp-controller="Home" asp-action="Privacy">@language.Getkey("Gizlilik")</a>
                            </li>
                        </ul>*@
                </div>
                <div class="nav-wrapper">
                    <div style="color:darkgray">


                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li><a style="color: darkgray" class="nav-link" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-Tr">Tr</a></li>

                            <li><a style="color: darkgray" class="nav-link" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US">En</a></li>

                        </ul>
                    </div>

                </div>
            </div>
        </nav>


    </main>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">@language.Getkey("Gizlilik Politikası")</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">@language.Getkey("Şartlar")</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" asp-controller="Home" asp-action="Privacy">@language.Getkey("İletişim")</a>
                </div>
            </div>
        </div>
    </footer>
    @*Bootstrap core JS*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  
    <script src="~/template/js/scripts.js"></script>
</body>
@await RenderSectionAsync("Scripts", required: false)

</html>